// @ts-expect-error - No types generated by vercel
import { VERCEL_URL } from "$env/static/private";
import type { LayoutServerLoad } from "./$types";
import { CONTRACT_NAME } from '$env/static/private';

export const load: LayoutServerLoad = () => {
  return {
    vercelUrl: VERCEL_URL,
    contractName: CONTRACT_NAME,
  };
};
